### GET ALL PRODUCTS
GET http://127.0.0.1:8000/products HTTP/1.1

### GET ONE PRODUCT
GET http://127.0.0.1:8000/products/a04 HTTP/1.1

### CREATE NEW PRODUCT
POST http://127.0.0.1:8000/create HTTP/1.1

Content-Type: 'application/json; charset=UTF-8'

{
  "code": "a05",
  "purchase_price": 754757,
  "sale_price": 4634643,
  "description": "dadasfsaf"
}

### UPDATE ONE PRODUCT
POST http://127.0.0.1:8000/update/a05 HTTP/1.1

Content-Type: 'application/json; charset=UTF-8'

{
  "code": "a05",
  "purchase_price": 1111111,
  "sale_price": 4634643,
  "description": "vbvbvc"
}