# Generated by Django 4.1.7 on 2023-03-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['code']},
        ),
    ]
